---
# 네임스페이스 작성 (별도의 프로젝트 공간)
apiVersion: v1
kind: Namespace
metadata: 
  name: project

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: project-lb
  namespace: project
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 80           # LB 포트. 
    targetPort: 80
 
